import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageJson = JSON.parse(
  readFileSync(join(__dirname, "..", "package.json"), "utf-8"),
);

const content = `// Auto-generated by scripts/generate-version.js
export const VERSION = "${packageJson.version}";
`;

mkdirSync(join(__dirname, "..", "src"), { recursive: true });
writeFileSync(join(__dirname, "..", "src", "version.ts"), content);
console.log(`Generated version.ts with version ${packageJson.version}`);
